//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalEmpleados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portal_EmpleadosEntities : DbContext
    {
        public Portal_EmpleadosEntities()
            : base("name=Portal_EmpleadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<listaChequeo_diaria_items> listaChequeo_diaria_items { get; set; }
        public virtual DbSet<listaChequeo_diaria_respuestas> listaChequeo_diaria_respuestas { get; set; }
        public virtual DbSet<listaChequeo_mensual_items> listaChequeo_mensual_items { get; set; }
        public virtual DbSet<listaChequeo_mensual_respuestas> listaChequeo_mensual_respuestas { get; set; }
    }
}
